### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by dshumakerUT** [crivotz/nv-ide#13]
No description provided.

**Comment by crivotz** [comment]
Can you add some more information :D ?

**Comment by danshumaker** [comment]
So sorry , this accidentally submitted using the github otto or orta plug in.   I was cleaning out plugins i dont use and wanted to test this out before removing it.  The good news is that it definitely works!!! 😁

**Comment by crivotz** [comment]
Don't worry 😉

**Comment by dshumakerUT** [comment]
It was the octo one.  Couldn't remember the spelling :) https://github.com/crivotz/nv-ide/blob/master/lua/plugins.lua#L83
