### ISSUE TITLE
personal configuration separation

### ISSUE THREAD

**Issue by nonogakhi** [crivotz/nv-ide#21]
Hi, Thanks for the great IDE.

Where basic configurations such as vim.g.mapleader are expected to be set. I created a init.lua in ~/.config/nvim/lua/user/ but it didn't pickup the mapleader.

Ideally I would like to be able to pull frequently from nv-ide repo without having to manage merge conflict with my own customization.

Thanks in advance

**Comment by nonogakhi** [comment]
I ended up adding vim.g.mapleader = ' ' on top of settings/init.lua for the moment but I think it would be great if we can extend the configs so that user configs which are in gitignore are picked before nv-ide. I'm keen on working on a PR if you have some suggestions.

**Comment by crivotz** [comment]
Hi,
thanks for the great suggestion PR is always welcome.
You might think about checking for a file and if not found proceed with defaults.

I'm sorry that these problems come up from time to time, the project is mainly my operational setup and I didn't think it would collect consensus :D More than anything else I thought it could serve as an eventual boilerplate for configuring some plugins

Thanks again

**Comment by nonogakhi** [comment]
Thanks for the clarification, yeah I like it very much. Hopefully with more consensus we will be able to take that to the next level
