### ISSUE TITLE
neovim 0.7

### ISSUE THREAD

**Issue by jasperstam** [crivotz/nv-ide#25]
I have several minor issues now, probably relating to the version of neovim I have installed. 0.7.2 or something.

I previously had to comment out line #31 in ~/.config/lua/settings/init.lua to get rid of a "splitkeep" error.
Suddenly almost everything began working, so I went back and uncommented the line, but could not reproduce that error again.

So now when starting nvim I get this;
```
  Error detected while processing /root/.config/nvim/plugin/packer_compiled.lua:
Feline needs 'termguicolors' to be enabled to work properly                                
Please do `:help 'termguicolors'` in Neovim for more information
E355: Unknown option: winbar     
minimap: this plugin requires code-minimap installed.
Press ENTER or type command to continue            
```
I searched through the packer_compiled.lua file, but do not see anything about winbar. I found some reference to a similar missing "winbar" problem, but no way for me to fix what I've got going on.
[{edit: actually I was able to move ahead a little bit on the code-minimap issue by running ``` sudo apt install libclang-dev g++ -y ``` , then ``` cargo install minimap ``` succeeded. will edit again if still greater success is realized. }
{REedit: even though ``` cargo install minimap ``` succeeded, I think it was the wrong package, because I needed code-minimap instead. I ran this other line, which succeeded also, ``` # cargo install --locked code-minimap ``` then I only had to Sync plugins in nvim, and now I have a working minimap!}
so now when I start nvim I only get 
```
               Error detected while processing /root/.config/nvim/plugin/packer_compiled.lua:
Feline needs 'termguicolors' to be enabled to work properly                                
Please do `:help 'termguicolors'` in Neovim for more information
E355: Unknown option: winbar     
```
errors.]

**Comment by crivotz** [comment]
Hi @jasperstam,
as you identified many problems are related to the version you are using.
If you will start to use the `stable` version you would still have some problems because I mainly work using the `nightly` version.

For example `winbar` has been merge into stable while `splitkeep` not yet.
However I have a branch called `neovim-stable` that does not introduce these issues, although sometimes it can get behind compared to the main branch.

;)
