### ISSUE TITLE
:PackerInstall error

### ISSUE THREAD

**Issue by ryanNewcodeer123** [crivotz/nv-ide#26]
Hi, I have just cloned the file and cd into the .config file and ln it, but when I open nvim and typed: PackerInstall, it said: E492: No an editor command: PackerInstall.
 What to do?
I am using Windows.

![Ubuntu 22 04 1 LTS 30_10_2022 4_12_23 PM](https://user-images.githubusercontent.com/110335999/198889365-94e4bc17-5168-489b-b7ce-16edd59e20a5.png)

**Comment by crivotz** [comment]
Closed. See #28
