### ISSUE TITLE
error when opening nvim

### ISSUE THREAD

**Issue by ryanNewcodeer123** [crivotz/nv-ide#28]
hi, I have just cd into the .config folder and type the next line and opened nvim, but with it open, it shows the following:
![Screenshot 2022-10-31 203821](https://user-images.githubusercontent.com/110335999/199105846-2d89ba0e-ab67-4ffd-b256-c90b962e4c84.png)
What to do?

**Comment by ryanNewcodeer123** [comment]
sorry, it is just the first time as it shows >120 messages at the same time, after that, it just takes < 3 sec to open. 
Thanks so much!!! 🤟

**Comment by crivotz** [comment]
Sorry for the delay but I was on vacation :)
I have seen the various issues. Were you able to get the configuration started?

**Comment by ryannewcomer** [comment]
Yes! It all working now, thanks so much.

**Comment by ryannewcomer** [comment]
hi, i got an error. I want to tye the tab key and it asid:

![Screenshot 2022-11-02 203025](https://user-images.githubusercontent.com/88273136/199596453-9c53b5ca-717d-428a-91c3-3764924ff772.png)
