### ISSUE TITLE
g:gutentags_enabled back to 1

### ISSUE THREAD

**Issue by KoBruhh** [crivotz/nv-ide#33]
I have just installed your IDE. Tbh pretty good one. but I am getting an error while loading it:

![Screenshot_20230114_220103](https://user-images.githubusercontent.com/101834410/212491679-501dd337-9029-4b86-be1a-2c0817be325c.png)

**Comment by crivotz** [comment]
Need to install ctags, I use this [universal-ctags](https://github.com/universal-ctags/ctags)
