### ISSUE TITLE
do not tempt me 

### ISSUE THREAD

**Issue by txl263** [crivotz/nv-ide#34]
![image](https://user-images.githubusercontent.com/969317/218188062-7e6442c4-1ddc-43b1-ab58-5b685cfba8bc.png)

Every time the cursor moves 10 rows or 10 columns, a message will pop up and freeze for a few seconds.
Had the same problem on two different machines（MacOS and archlinux）
Which plugin caused this or how to query which plugin caused it?

**Comment by crivotz** [comment]
You can remove this line from init.lua
https://github.com/crivotz/nv-ide/blob/cb0617c67366fc6ed4838bfc1301b441ac4c830c/init.lua#L6
