### ISSUE TITLE
Thanks & Obsolete Plugin

### ISSUE THREAD

**Issue by bmulholland** [crivotz/nv-ide#4]
Hey - thanks for this repo, I've used it extensively in [crafting my own](https://github.com/bmulholland/dotfiles/tree/lua/neovim) :)

While doing that, I noticed that [vim-tmux-focus-events is no longer necessary](https://github.com/tmux-plugins/vim-tmux-focus-events#tmux-focus-eventsvim), so you can remove it.

**Comment by crivotz** [comment]
Hi, thank you so much for the advice.
I'm glad my configuration is useful to you  👍🏻
