### ISSUE TITLE
Randomly noticed this spelling error

### ISSUE THREAD

**Issue by killerqueer** [crivotz/nv-ide#43]
Hi! I was browsing your config to see how you set up nvim-ufo and noticed this small spelling error in the following keymapping description and wanted to let you know about it <sup>~~because it made me laugh~~</sup>

https://github.com/crivotz/nv-ide/blob/8aba6deefdc2ed26db4673381dbaf752632c093a/lua/config/plugins/nvim-ufo.lua#L10

**Comment by crivotz** [comment]
LOL, maybe I could leave it :smile:.

Thanks
